# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Run a multi-line script'
  inputs:
    azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az extension add --name spring
      az spring build-service build update -n $(APP) -s $(BUILD_SI) -g $(GROUP) --source-path . --build-env BP_JVM_VERSION=17

- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/5c6097b3-0798-4146-8d81-1e3ef0686c2d/resourceGroups/asa-e-rg-01/providers/Microsoft.AppPlatform/Spring/asa-e-si-02'
    AppName: $(APP)
    DeploymentType: 'CustomContainer'
    UseStagingDeployment: false
    DeploymentName: 'default'
    RegistryServer: $(REGISTRY)
    RegistryUsername: $(REG_USER)
    RegistryPassword: $(REG_PASSWD)
    ImageName: 'result'      
# - task: AzureSpringCloud@0
#   inputs:
#     azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
#     Action: 'Deploy'
#     AzureSpringCloud: '/subscriptions/5c6097b3-0798-4146-8d81-1e3ef0686c2d/resourceGroups/asa-e-rg-01/providers/Microsoft.AppPlatform/Spring/asa-e-si-02'
#     AppName: 'hello-world'
#     DeploymentType: 'CustomContainer'
#     UseStagingDeployment: false
#     DeploymentName: 'default'
#     RegistryServer: $(REGISTRY)
#     RegistryUsername: $(REG_USER)
#     RegistryPassword: $(REG_PASSWD)
#     ImageName: 'result'