# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzureSpringCloud@0
  inputs:
    azureSubscription: 'anish-patel-playground(1)(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/5c6097b3-0798-4146-8d81-1e3ef0686c2d/resourceGroups/asa-e-rg-01/providers/Microsoft.AppPlatform/Spring/asa-e-si-01'
    AppName: 'hello-world'
    UseStagingDeployment: false
    Builder: '/subscriptions/5c6097b3-0798-4146-8d81-1e3ef0686c2d/resourceGroups/asa-e-rg-01/providers/Microsoft.AppPlatform/Spring/asa-e-si-01/buildServices/default/builders/java-test-builder'
    RuntimeVersion: 'Java_17'