# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'Run a one-line script'

- script: |
    ls -alFhrt
    pwd
  displayName: 'Run a multi-line script'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az extension add --name spring
      az version
      ls -alFhrt
      az spring build-service build update -n hello-world -s asa-e-si-01 -g asa-e-rg-01 --source-path . --build-env BP_JVM_VERSION=17