# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
    - pipeline: scan
      source: scan
      trigger: true

  repositories:
    - repository: checksums
      type: git 
      name: hello-world/container-checksums
pool:
  vmImage: ubuntu-latest

steps:
- checkout: checksums
  persistCredentials: true
- checkout: self
# - task: AzureCLI@2
#   displayName: 'Build $(APP) from source'
#   inputs:
#     azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       pwd
#       az config set core.no_color=true
#       az extension add --name spring
#       az spring build-service build update -n $(APP) -s $(BUILD_SI) -g $(GROUP) --source-path ./hello-world --build-env BP_JVM_VERSION=17 | tee build.txt
#       export CHECKSUM=$( cat build.txt| grep Images | awk -F "(" '{print $2}' )   
#       python3 -c 'import os; print(os.getenv("CHECKSUM").strip("):"))' > checksum
#       cat checksum
#       cp checksum  ./container-checksums
- script: |
    cd ./container-checksums
    git config user.email pipeline@buildsh.it 
    git config user.name "Pipeline"
    git branch -r
    git checkout main
    # git add checksum
    # git commit -m "new checksum"
    # git push origin main