resources:
  pipelines:
    - pipeline: build
      source: build

trigger: none

variables:
  - group: 'hello-world'

parameters:
  - name: APP
    type: string
    default: hello-world-ado

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureSpringCloud@0
  displayName: 'Deploy $(APP) from image registry'
  inputs:
    azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
    Action: 'Deploy'
    AzureSpringCloud: '/subscriptions/5c6097b3-0798-4146-8d81-1e3ef0686c2d/resourceGroups/asa-e-rg-01/providers/Microsoft.AppPlatform/Spring/asa-e-si-02'
    AppName: $(APP)
    DeploymentType: CustomContainer
    UseStagingDeployment: false
    DeploymentName: 'default'
    RegistryServer: $(REGISTRY)
    RegistryUsername: $(REG_USER)
    RegistryPassword: $(REG_PASSWD)
    ImageName: $(IMG_NAME)
    EnvironmentVariables: -env "deployed from ado"