resources:
  pipelines:
    - pipeline: build
      source: build

trigger: none

parameters:
  - name: APP
    type: string
    default: hello-world-prod

variables:
  - group: 'hello-world'
  - name: APP
    value: ${{ parameters.APP }}

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'deploy $(APP) from registry'
  inputs:
    azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    arguments: $(APP) $(BUILD_SI) $(DEPLOY_SI) $(GROUP) $(IMG_NAME) $(REG_PASSWD) $(REG_USER) $(REGISTRY)
    inlineScript: |
      az extension add --name spring
      az spring app deploy -n $(APP) -s $(DEPLOY_SI) -g $(GROUP) --container-image $(IMG_NAME) --container-registry $(REGISTRY) --registry-password $(REG_PASSWD) --registry-username $(REG_USER)  --env "env=deployed from cli"