resources:
  pipelines:
    - pipeline: build
      source: build
      trigger: true

  repositories:
    - repository: checksums
      type: git 
      name: hello-world/container-checksums

parameters:
  - name: APP
    type: string
    default: hello-world-ado

variables:
  - group: 'hello-world'
  - name: APP
    value: ${{ parameters.APP }}

pool:
  vmImage: ubuntu-latest

steps:
- checkout: checksums
- script: |
    CHECKSUM=`cat checksum`
    echo "##vso[task.setvariable variable=CHECKSUM]$CHECKSUM"
  displayName: get Checksum
- script: |
    echo $CHECKSUM
  
# - task: AzureSpringCloud@0
#   displayName: 'Deploy $(APP) from image registry'
#   inputs:
#     azureSubscription: 'anish-patel-playground(5c6097b3-0798-4146-8d81-1e3ef0686c2d)'
#     Action: 'Deploy'
#     AzureSpringCloud: '/subscriptions/5c6097b3-0798-4146-8d81-1e3ef0686c2d/resourceGroups/asa-e-rg-01/providers/Microsoft.AppPlatform/Spring/asa-e-si-02'
#     AppName: $(APP)
#     DeploymentType: CustomContainer
#     UseStagingDeployment: false
#     DeploymentName: 'default'
#     RegistryServer: $(REGISTRY)
#     RegistryUsername: $(REG_USER)
#     RegistryPassword: $(REG_PASSWD)
#     ImageName: $(IMG_NAME)
#     EnvironmentVariables: -env "deploying from ado pipelines"