name: AzureSpringAppsBuild
on: [push, workflow_dispatch]
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 5c6097b3-0798-4146-8d81-1e3ef0686c2d

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        container-sha: ${{ steps.create-build.outputs.test}}
    name: deploy to production with source code
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create/update build
        id: create-build
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: build
          service-name: asa-e-si-01
          build-name: hello-world
          runtime-version: Java_17
          build-env: -BP_JVM_VERSION 17
          package: ${{ env.ASC_PACKAGE_PATH }}
  checksum:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - env:
          CHECKSUM: ${{needs.build.outputs.container-sha }}
        run: echo $CHECKSUM && cat $GITHUB_OUTPUT