name: AzureSpringAppsDeploy
on:
  workflow_run:
    workflows: ["AzureSpringAppsBuild"]
    types:
      - completed

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: 5c6097b3-0798-4146-8d81-1e3ef0686c2d
  REG_USER: ${{ vars.REG_USER }}
  REG_PASSWD: ${{ secrets.REG_PASSWD}}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with container image
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy custom container image
        uses: Azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: asa-e-si-02
          app-name: hello-world-prod
          deployment-name: default
          container-registry: akptest.azurecr.io
          registry-username: ${{ env.REG_USER }}
          registry-password: ${{ secrets.REG_PASSWD}}
          container-image: hello-world-gh:result
          environment-variables: -env GHA